"""Drift guard for the generated Unicode default-ignorable table.

`src/unicode_tables.rs` is generated by `tools/gen_unicode_tables.py` from the
running Unicode version's `Default_Ignorable_Code_Point` property. This test
recomputes that property and asserts the committed Rust table still matches, so a
Unicode version bump (or a hand-edit) that leaves the table stale fails CI with an
actionable message instead of silently opening a hole.
"""

from __future__ import annotations

import importlib.util
import re
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RUST_TABLE = REPO / "src" / "unicode_tables.rs"
GENERATOR = REPO / "tools" / "gen_unicode_tables.py"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_unicode_tables", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def _parse_rust_ranges() -> list[tuple[int, int]]:
    text = RUST_TABLE.read_text(encoding="utf-8")
    body = text.split("&[", 1)[1]
    return [
        (int(lo, 16), int(hi, 16))
        for lo, hi in re.findall(r"\(0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+)\)", body)
    ]


def test_rust_table_matches_current_unicode_property() -> None:
    gen = _load_generator()
    expected = gen.to_ranges(gen.default_ignorable_codepoints())
    committed = _parse_rust_ranges()
    assert committed == expected, (
        "src/unicode_tables.rs is stale for "
        f"Unicode {unicodedata.unidata_version}. "
        "Regenerate it with: python tools/gen_unicode_tables.py --write"
    )


def test_generated_table_covers_known_invisibles() -> None:
    gen = _load_generator()
    di = gen.default_ignorable_codepoints()
    # Spot-check the characters the sanitizer must treat as ignorable.
    for cp in (0x00AD, 0x200B, 0x200E, 0x2060, 0xFEFF, 0xFE0F, 0xE0001, 0xE0061, 0xE0100):
        assert cp in di, f"U+{cp:04X} missing from default-ignorable set"
    # And characters that must NOT be treated as ignorable (benign Arabic marks).
    for cp in (0x0600, 0x06DD, 0x070F):
        assert cp not in di, f"U+{cp:04X} wrongly treated as ignorable"


def test_reserved_tag_range_is_covered() -> None:
    # The reserved default-ignorable tail (E01F0..E0FFF) must be covered so a
    # future assignment in that block is stripped, not leaked.
    committed = _parse_rust_ranges()
    assert any(lo <= 0xE0500 <= hi for lo, hi in committed)
