#!/usr/bin/env python3
"""Generate the Unicode default-ignorable table used by the Rust core.

`Default_Ignorable_Code_Point` is a *derived* Unicode property. Per the UCD
(DerivedCoreProperties.txt) it is:

    Other_Default_Ignorable_Code_Point
  + Cf  (General_Category = Format)
  + Variation_Selector
  - White_Space
  - FFF9..FFFB           (interlinear annotation anchors)
  - 13430..1343F         (Egyptian Hieroglyph format controls)
  - Prepended_Concatenation_Mark

The volatile part — the `Cf` category — is read from the running Python's
`unicodedata`, so a Unicode version bump automatically pulls in newly-added
format characters. The stable definitional pieces below are small, rarely
change, and are each cited to the UCD. This is what keeps the hand-maintained
table from silently rotting: regenerate (or run the drift test) and any new
default-ignorable character is caught.

Usage:
    python tools/gen_unicode_tables.py            # print Rust source
    python tools/gen_unicode_tables.py --write    # write src/unicode_tables.rs
"""
from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

# Other_Default_Ignorable_Code_Point (UCD PropList.txt)
OTHER_DI: list[tuple[int, int]] = [
    (0x034F, 0x034F),
    (0x115F, 0x1160),
    (0x17B4, 0x17B5),
    (0x2065, 0x2065),
    (0x3164, 0x3164),
    (0xFFA0, 0xFFA0),
    (0xFFF0, 0xFFF8),
    (0xE0000, 0xE0000),
    (0xE0002, 0xE001F),
    (0xE0080, 0xE00FF),
    (0xE01F0, 0xE0FFF),
]
# Variation_Selector (UCD PropList.txt)
VARIATION_SELECTOR: list[tuple[int, int]] = [
    (0x180B, 0x180D),
    (0x180F, 0x180F),
    (0xFE00, 0xFE0F),
    (0xE0100, 0xE01EF),
]
# Subtractions from the derivation.
INTERLINEAR = [(0xFFF9, 0xFFFB)]
EGYPTIAN_FORMAT = [(0x13430, 0x1343F)]
# Prepended_Concatenation_Mark (UCD PropList.txt): Cf characters that are visible
# marks in Arabic/Syriac and must NOT be treated as ignorable.
PREPENDED_CONCAT_MARK = [
    (0x0600, 0x0605),
    (0x06DD, 0x06DD),
    (0x070F, 0x070F),
    (0x0890, 0x0891),
    (0x08E2, 0x08E2),
    (0x110BD, 0x110BD),
    (0x110CD, 0x110CD),
]


def _expand(ranges: list[tuple[int, int]]) -> set[int]:
    out: set[int] = set()
    for lo, hi in ranges:
        out.update(range(lo, hi + 1))
    return out


def default_ignorable_codepoints() -> set[int]:
    di: set[int] = set()
    for cp in range(0x110000):
        if unicodedata.category(chr(cp)) == "Cf":
            di.add(cp)
    di |= _expand(OTHER_DI)
    di |= _expand(VARIATION_SELECTOR)
    subtract = set()
    for cp in range(0x110000):
        # White_Space is a binary property; approximate via category Zs/Zl/Zp
        # plus the ASCII/So whitespace controls that carry it. unicodedata has no
        # direct White_Space accessor, so use the explicit small set below.
        pass
    subtract |= _expand(INTERLINEAR)
    subtract |= _expand(EGYPTIAN_FORMAT)
    subtract |= _expand(PREPENDED_CONCAT_MARK)
    # White_Space members that are also Cf/format-adjacent. The only relevant one
    # is none in Cf (spaces are Zs, not Cf), so no White_Space subtraction from
    # the Cf set is needed for correctness of the ignorable table.
    return di - subtract


def to_ranges(cps: set[int]) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for cp in sorted(cps):
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], cp)
        else:
            ranges.append((cp, cp))
    return ranges


def render_rust(ranges: list[tuple[int, int]]) -> str:
    lines = [
        "// @generated by tools/gen_unicode_tables.py — do not edit by hand.",
        f"// Source: Unicode {unicodedata.unidata_version} "
        "Default_Ignorable_Code_Point (derived).",
        "// Regenerate after a Unicode version bump; the drift test in",
        "// tests/test_unicode_tables.py fails if this list falls behind.",
        "",
        "/// Codepoint ranges with the Unicode Default_Ignorable_Code_Point property.",
        "pub const DEFAULT_IGNORABLE_RANGES: &[(u32, u32)] = &[",
    ]
    for lo, hi in ranges:
        lines.append(f"    (0x{lo:04X}, 0x{hi:04X}),")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ranges = to_ranges(default_ignorable_codepoints())
    rust = render_rust(ranges)
    if "--write" in sys.argv:
        dest = Path(__file__).resolve().parents[1] / "src" / "unicode_tables.rs"
        dest.write_text(rust, encoding="utf-8")
        print(f"wrote {dest} ({len(ranges)} ranges, Unicode {unicodedata.unidata_version})")
    else:
        print(rust)


if __name__ == "__main__":
    main()
