#!/usr/bin/env python3
"""Generate permitted standardized/emoji pairs from pinned Unicode data.

Sources (Unicode 17.0.0, licensed under https://www.unicode.org/license.txt):
https://www.unicode.org/Public/17.0.0/ucd/StandardizedVariants.txt
https://www.unicode.org/Public/17.0.0/ucd/emoji/emoji-variation-sequences.txt

IVD sequences are a separate registry. The core accepts extended selectors on
Han ideographs for compatibility, without claiming registered-pair validation.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

VERSION = "17.0.0"
DATA = Path(__file__).parent / "unicode-data" / VERSION
SOURCES = ("StandardizedVariants.txt", "emoji-variation-sequences.txt")


def render_rust() -> str:
    pairs: set[tuple[int, int]] = set()
    source_comments: list[str] = []
    for name in SOURCES:
        data = (DATA / name).read_bytes()
        source_comments.append(f"// {name}: SHA256 {hashlib.sha256(data).hexdigest()}")
        pairs.update(
            (int(base, 16), int(selector, 16))
            for base, selector in re.findall(
                r"^([0-9A-F]+)\s+([0-9A-F]+)\s*;", data.decode("utf-8"), re.MULTILINE
            )
        )
    lines = [
        "// @generated by tools/gen_variation_sequences.py; do not edit by hand.",
        "// Unicode data license: https://www.unicode.org/license.txt",
        *source_comments,
        f'pub const VARIATION_DATA_VERSION: &str = "{VERSION}";',
        "pub const STANDARDIZED_VARIATION_PAIRS: &[(u32, u32)] = &[",
        *(f"    (0x{base:X}, 0x{selector:X})," for base, selector in sorted(pairs)),
        "];",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    destination = Path(__file__).resolve().parents[1] / "src" / "variation_tables.rs"
    destination.write_text(render_rust(), encoding="utf-8")
    print(f"wrote {destination}")
